package gamejam:game;

world interactable-entity {
    import game-host;

    // Event listeneres (optionally called based on the interests)

    export startup: func() -> u64;
    export interacted: func();
}