[entities.house_1]
id = "house_1"
tags = ["house"]
script_path = "scripts/test_entity_script.wasm"

[entities.house_1.idle_animation]
sprite_name = "house_1"
animation_name = "idle"
duration_millis = 1000

[entities.house_1.distance_based_animations.50]
sprite_name = "house_1"
animation_name = "glowing"
duration_millis = 1000

[entities.lamp_post]
id = "lamp_post"
tags = ["decorative"]

[entities.lamp_post.idle_animation]
sprite_name = "lamp_post"
animation_name = "idle"
duration_millis = 1000

[entities.lamp_post.distance_based_animations.70]
sprite_name = "lamp_post"
animation_name = "swinging"
duration_millis = 700

[entities.lever]
id = "lever"
tags = ["lever", "interactable"]
script_path = "scripts/lever_script.wasm"

[entities.door]
id = "door"
tags = ["lever", "interactable"]
script_path = "scripts/door_script.wasm"

[entities.platform_1]
id = "platform_1"
tags = ["platform"]
script_path = "scripts/platform_script.wasm"
script_params = ["sprite-name=platform_1"]


# Rubble
[entities.rubble-sign-up-diag]
id = "rubble-sign-up-diag"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=sign_diag_up", "death-duration=200"]

[entities.rubble-reeds]
id = "rubble-reeds"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=reeds", "death-duration=200"]

[entities.rubble-box-1]
id = "rubble-box-1"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=rubble_box_1", "death-duration=200"]


[entities.rubble-rock-wall]
id = "rubble-rock-wall"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=rubble_rock_wall",
    "death-duration=200",
    "physical=true",
    "collider-size=32,16"
]


[entities.fireplace]
id = "firepalce"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=fireplace",
    "invulnerable=true"
]


# Enemies


[entities.enemy-what]
id = "enemy-what"
tags = ["enemy", "what"]
script_path = "scripts/simple_enemy.wasm"
script_params = [
    "sprite-name=what_sprite"
]

[entities.enemy-bob]
id = "enemy-bob"
tags = ["enemy", "bob"]
script_path = "scripts/enemy_biped.wasm"
script_params = [
    "sprite-name=bob",
    "idle-animation=idle",
    "walking-animation=run",
    "windup-animation=windup",
    "wound-animation=wound",
    "attack-animation=attack",
    "death-animation=death",
    "dead-animation=dead",
    "staggered-animation=staggered",
    "attack-range=48",
    "aggro-range=150",
    "windup-attack-delay=200",
    "attack-duration=200"
]
