[entities.house_1]
id = "house_1"
tags = ["house"]
script_path = "scripts/test_entity_script.wasm"

[entities.house_1.idle_animation]
sprite_name = "house_1"
animation_name = "idle"
duration_millis = 1000

[entities.house_1.distance_based_animations.50]
sprite_name = "house_1"
animation_name = "glowing"
duration_millis = 1000

[entities.lamp_post]
id = "lamp_post"
tags = ["decorative"]

[entities.lamp_post.idle_animation]
sprite_name = "lamp_post"
animation_name = "idle"
duration_millis = 1000

[entities.lamp_post.distance_based_animations.70]
sprite_name = "lamp_post"
animation_name = "swinging"
duration_millis = 700

[entities.lever]
id = "lever"
tags = ["lever", "interactable"]
script_path = "scripts/lever_script.wasm"

[entities.door]
id = "door"
tags = ["lever", "interactable"]
script_path = "scripts/door_script.wasm"


# Rubble
[entities.rubble-sign-up-diag]
id = "rubble-sign-up-diag"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=sign_diag_up", "death-duration=200"]

[entities.rubble-reeds]
id = "rubble-reeds"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=reeds", "death-duration=200"]

[entities.rubble-box-1]
id = "rubble-box-1"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=rubble_box_1", "death-duration=200"]


[entities.rubble-rock-wall]
id = "rubble-rock-wall"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=rubble_rock_wall",
    "death-duration=200",
    "physical=true",
    "collider-size=32,16"
]


[entities.fireplace]
id = "firepalce"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=fireplace",
    "invulnerable=true"
]