[entities.game_level]
id = "game_level"
tags = []
script_path = "scripts/game_level_script.wasm"
script_params = [
    "music-file=audio/earth_is_all_we_have.ogg"
]


[entities.house_1]
id = "house_1"
tags = ["house"]
script_path = "scripts/test_entity_script.wasm"
z = 2.0

[entities.house_1.idle_animation]
sprite_name = "house_1"
animation_name = "idle"
duration_millis = 1000

[entities.house_1.distance_based_animations.50]
sprite_name = "house_1"
animation_name = "glowing"
duration_millis = 1000

[entities.lamp_post]
id = "lamp_post"
tags = ["decorative"]
z = 2.0

[entities.lamp_post.idle_animation]
sprite_name = "lamp_post"
animation_name = "idle"
duration_millis = 1000

[entities.lamp_post.distance_based_animations.70]
sprite_name = "lamp_post"
animation_name = "swinging"
duration_millis = 700

[entities.lever]
id = "lever"
tags = ["lever", "interactable"]
script_path = "scripts/lever_script.wasm"
z = 2.0

[entities.door]
id = "door"
tags = ["lever", "interactable"]
script_path = "scripts/door_script.wasm"
z = 2.0

[entities.platform_1]
id = "platform_1"
tags = ["platform"]
script_path = "scripts/platform_script.wasm"
script_params = ["sprite-name=platform_1"]
z = 2.0

# Rubble
[entities.rubble-sign-up-diag]
id = "rubble-sign-up-diag"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=sign_diag_up", "death-duration=200", "death-sound=audio/wood-small.wav"]
z = 2.0

[entities.rubble-sign]
id = "rubble-sign"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=sign", "death-duration=200", "death-sound=audio/wood-small.wav"]
z = 2.0

[entities.rubble-terminal]
id = "rubble-terminal"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=terminal", "invulnerable=true"]
z = 2.0

[entities.rubble-reeds]
id = "rubble-reeds"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=reeds", "death-duration=200", "death-sound=audio/cloth.wav"]
z = 2.0

[entities.rubble-box-1]
id = "rubble-box-1"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=rubble_box_1", "death-duration=200", "death-sound=audio/wood-small.wav"]
z = 2.0

[entities.rubble-rock-wall]
id = "rubble-rock-wall"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=rubble_rock_wall",
    "death-duration=200",
    "physical=true",
    "collider-size=32,16",
    "death-sound=audio/stones_01.ogg"
]
z = 2.0

[entities.fireplace]
id = "firepalce"
tags = ["rubble"]
script_path = "scripts/rubble_script.wasm"
script_params = [
    "sprite-name=fireplace",
    "invulnerable=true"
]
z = 2.0

# Enemies

[entities.egg_spitter]
id = "egg_spitter"
tags = ["enemy", "egg_spitter"]
script_path = "scripts/egg_spitter.wasm"
script_params = [
    "sprite-name=egg_spitter",
    "attack-sound=audio/monsters/bite1.wav",
    "idle-animation=idle",
    "attack-animation=attack",
]
z = 2.0

[entities.egg_projectile]
id = "egg_projectile"
tags = ["enemy", "egg_projectile"]
script_path = "scripts/egg_projectile.wasm"
script_params = [
    "sprite-name=egg_projectile",
    "idle-animation=idle",
    "explode-animation=splat",
    "explode-sound=audio/monsters/bite1.wav",
]
z = 2.0


[entities.enemy-what]
id = "enemy-what"
tags = ["enemy", "what"]
script_path = "scripts/simple_enemy.wasm"
script_params = [
    "sprite-name=what_sprite",
    "attack-sound=audio/monsters/bite1.wav",
    "death-sound=audio/monsters/death1.wav",
    "hit-sound=audio/monsters/hit.ogg",
]

[entities.enemy-bob]
id = "enemy-bob"
tags = ["enemy", "bob"]
script_path = "scripts/enemy_biped.wasm"
script_params = [
    "sprite-name=bob",
    "idle-animation=idle",
    "walking-animation=run",
    "windup-animation=windup",
    "wound-animation=wound",
    "attack-animation=attack",
    "death-animation=death",
    "dead-animation=dead",
    "staggered-animation=staggered",
    "attack-range=48",
    "aggro-range=150",
    "windup-attack-delay=50",
    "attack-duration=200",
    "attack-sound=audio/monsters/ogre_attack.wav",
    "death-sound=audio/monsters/ogre_death.wav",
    "hit-sound=audio/monsters/ogre_hit.wav",
]


[entities.enemy-springer]
id = "enemy-springer"
tags = ["enemy", "springer"]
script_path = "scripts/enemy_springer.wasm"
script_params = [
    "sprite-name=springer",
    "idle-animation=idle",
    "attack-animation=attack",
    "death-animation=death",
    "dead-animation=dead",
    "attack-range=32",
    "attack-damage=20",
    "attack-duration=200",
    "attack-sound=audio/monsters/ogre_attack.wav",
    "death-sound=audio/monsters/ogre_death.wav",
    "hit-sound=audio/monsters/ogre_hit.wav",
]

# Gameplay

[entities.pedestal]
id = "pedestal"
tags = []
script_path = "scripts/rubble_script.wasm"
script_params = ["sprite-name=pedestal", "invulnerable=true"]
z = 2.0

[entities.pedestal_pickup]
id = "pedestal_pickup"
tags = []
script_path = "scripts/powerup_script.wasm"
script_params = ["sprite-name=pedestal_pickup", "invulnerable=true"]
z = 3.0