[sprites.terminal]
sprite_sheet_file_name = "sprites/terminal.png"
image_width = 32
image_height = 32
[sprites.terminal.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4




[sprites.player_attack]
sprite_sheet_file_name = "sprites/attack.png"
image_width = 64
image_height = 64

[sprites.player_attack.animations.down]
row = 0
frame_start_index = 0
frame_count = 5

[sprites.player_attack.animations.horizontal]
row = 1
frame_start_index = 0
frame_count = 5






[sprites.chest_simple]
sprite_sheet_file_name = "sprites/chest_simple.png"
image_width = 16
image_height = 16

[sprites.chest_simple.animations.locked]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.chest_simple.animations.opening]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.chest_simple.animations.open]
row = 1
frame_start_index = 5
frame_count = 1




# Enemies

[sprites.what_sprite]
sprite_sheet_file_name = "sprites/enemies/the_what.png"
image_width = 32
image_height = 32

[sprites.what_sprite.animations.run]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.idle]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.death]
row = 2
frame_start_index = 0
frame_count = 5

[sprites.what_sprite.animations.dead]
row = 2
frame_start_index = 4
frame_count = 1


# Neutrals


[sprites.bounce_fly]
sprite_sheet_file_name = "sprites/enemies/bounce_fly.png"
image_width = 32
image_height = 32

[sprites.bounce_fly.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4






# Rubble

[sprites.rubble_rock_wall]
sprite_sheet_file_name = "sprites/scenery/rock_wall.png"
image_width = 32
image_height = 32

[sprites.rubble_rock_wall.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.rubble_rock_wall.animations.death]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.rubble_rock_wall.animations.dead]
row = 1
frame_start_index = 3
frame_count = 1


[sprites.sign_diag_up]
sprite_sheet_file_name = "sprites/scenery/sign_diag_up.png"
image_width = 32
image_height = 32

[sprites.sign_diag_up.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.sign_diag_up.animations.death]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.sign_diag_up.animations.dead]
row = 1
frame_start_index = 5
frame_count = 1

[sprites.reeds]
sprite_sheet_file_name = "sprites/scenery/reeds.png"
image_width = 32
image_height = 32

[sprites.reeds.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.reeds.animations.death]
row = 1
frame_start_index = 0
frame_count = 8

[sprites.reeds.animations.dead]
row = 1
frame_start_index = 7
frame_count = 1










# Items


[sprites.item_heart]
sprite_sheet_file_name = "sprites/items/heart.png"
image_width = 32
image_height = 32

[sprites.item_heart.animations.full]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.item_heart.animations.half]
row = 1
frame_start_index = 0
frame_count = 1

[sprites.item_heart.animations.empty]
row = 2
frame_start_index = 0
frame_count = 1

# UI

[sprites.ui_healthbar]
sprite_sheet_file_name = "ui/healthbar.png"
image_width = 256
image_height = 64

[sprites.ui_healthbar.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1
