[sprites.terminal]
sprite_sheet_file_name = "sprites/terminal.png"
image_width = 32
image_height = 32
[sprites.terminal.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.player]
sprite_sheet_file_name = "sprites/guy.png"
image_width = 32
image_height = 32

[sprites.player.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.player.animations.run]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.player.animations.jump]
row = 2
frame_start_index = 0
frame_count = 4

[sprites.player.animations.fall]
row = 3
frame_start_index = 0
frame_count = 4

[sprites.player.animations.attack]
row = 4
frame_start_index = 0
frame_count = 4

[sprites.player.animations.attack_down]
row = 5
frame_start_index = 0
frame_count = 4

[sprites.player.animations.roll]
row = 6
frame_start_index = 0
frame_count = 6






[sprites.player_attack]
sprite_sheet_file_name = "sprites/attack.png"
image_width = 64
image_height = 64

[sprites.player_attack.animations.down]
row = 0
frame_start_index = 0
frame_count = 5

[sprites.player_attack.animations.horizontal]
row = 1
frame_start_index = 0
frame_count = 5



[sprites.lever]
sprite_sheet_file_name = "sprites/lever.png"
image_width = 32
image_height = 32

[sprites.lever.animations.open]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.lever.animations.closing]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.lever.animations.closed]
row = 2
frame_start_index = 0
frame_count = 1




[sprites.door_1]
sprite_sheet_file_name = "sprites/scenery/door_1.png"
image_width = 16
image_height = 48

[sprites.door_1.animations.closed]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.door_1.animations.opening]
row = 1
frame_start_index = 0
frame_count = 8

[sprites.door_1.animations.open]
row = 2
frame_start_index = 0
frame_count = 1



[sprites.chest_simple]
sprite_sheet_file_name = "sprites/chest_simple.png"
image_width = 16
image_height = 16

[sprites.chest_simple.animations.locked]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.chest_simple.animations.opening]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.chest_simple.animations.open]
row = 1
frame_start_index = 5
frame_count = 1





[sprites.platform_1]
sprite_sheet_file_name = "sprites/scenery/platform_1.png"
image_width = 64
image_height = 16

[sprites.platform_1.animations.ghost]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.platform_1.animations.materializing]
row = 1
frame_start_index = 0
frame_count = 7

[sprites.platform_1.animations.solid]
row = 2
frame_start_index = 0
frame_count = 1



# Enemies

[sprites.what_sprite]
sprite_sheet_file_name = "sprites/enemies/the_what.png"
image_width = 32
image_height = 32

[sprites.what_sprite.animations.run]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.idle]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.death]
row = 2
frame_start_index = 0
frame_count = 5

[sprites.what_sprite.animations.dead]
row = 2
frame_start_index = 4
frame_count = 1

[sprites.what_sprite.animations.attack]
row = 3
frame_start_index = 0
frame_count = 7




[sprites.springer]
sprite_sheet_file_name = "sprites/enemies/springer.png"
image_width = 32
image_height = 32

[sprites.springer.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.springer.animations.attack]
row = 1
frame_start_index = 0
frame_count = 7

[sprites.springer.animations.dead]
row = 2
frame_start_index = 0
frame_count = 1





[sprites.bob]
sprite_sheet_file_name = "sprites/enemies/bob.png"
image_width = 64
image_height = 64

[sprites.bob.animations.run]
row = 3
frame_start_index = 0
frame_count = 4

[sprites.bob.animations.idle]
row = 0
frame_start_index = 0
frame_count = 2

[sprites.bob.animations.death]
row = 4
frame_start_index = 0
frame_count = 6

[sprites.bob.animations.dead]
row = 4
frame_start_index = 5
frame_count = 1

[sprites.bob.animations.windup]
row = 1
frame_start_index = 0
frame_count = 3

[sprites.bob.animations.wound]
row = 1
frame_start_index = 2
frame_count = 1

[sprites.bob.animations.attack]
row = 2
frame_start_index = 0
frame_count = 5

[sprites.bob.animations.staggered]
row = 5
frame_start_index = 0
frame_count = 1



# Neutrals


[sprites.bounce_fly]
sprite_sheet_file_name = "sprites/enemies/bounce_fly.png"
image_width = 32
image_height = 32

[sprites.bounce_fly.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4






# Rubble

[sprites.rubble_rock_wall]
sprite_sheet_file_name = "sprites/scenery/rock_wall.png"
image_width = 32
image_height = 32

[sprites.rubble_rock_wall.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.rubble_rock_wall.animations.death]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.rubble_rock_wall.animations.dead]
row = 1
frame_start_index = 3
frame_count = 1


[sprites.rubble_box_1]
sprite_sheet_file_name = "sprites/scenery/box_1.png"
image_width = 32
image_height = 32

[sprites.rubble_box_1.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.rubble_box_1.animations.death]
row = 1
frame_start_index = 0
frame_count = 5

[sprites.rubble_box_1.animations.dead]
row = 2
frame_start_index = 0
frame_count = 1


# scenery
[sprites.fireplace]
sprite_sheet_file_name = "sprites/scenery/fireplace.png"
image_width = 64
image_height = 64

[sprites.fireplace.animations.idle]
row = 0
frame_start_index = 0
frame_count = 5


[sprites.sign_diag_up]
sprite_sheet_file_name = "sprites/scenery/sign_diag_up.png"
image_width = 32
image_height = 32

[sprites.sign_diag_up.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.sign_diag_up.animations.death]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.sign_diag_up.animations.dead]
row = 1
frame_start_index = 5
frame_count = 1


[sprites.sign]
sprite_sheet_file_name = "sprites/scenery/sign.png"
image_width = 32
image_height = 32

[sprites.sign.animations.death]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.sign.animations.dead]
row = 1
frame_start_index = 5
frame_count = 1


[sprites.sign.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.reeds]
sprite_sheet_file_name = "sprites/scenery/reeds.png"
image_width = 32
image_height = 32

[sprites.reeds.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.reeds.animations.death]
row = 1
frame_start_index = 0
frame_count = 8

[sprites.reeds.animations.dead]
row = 1
frame_start_index = 7
frame_count = 1



[sprites.pedestal]
sprite_sheet_file_name = "sprites/scenery/pedestal.png"
image_width = 32
image_height = 32

[sprites.pedestal.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1




[sprites.pedestal_pickup]
sprite_sheet_file_name = "sprites/scenery/pedestal_pickup.png"
image_width = 32
image_height = 32

[sprites.pedestal_pickup.animations.idle]
row = 0
frame_start_index = 0
frame_count = 6






# Items


[sprites.item_heart]
sprite_sheet_file_name = "sprites/items/heart.png"
image_width = 32
image_height = 32

[sprites.item_heart.animations.full]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.item_heart.animations.half]
row = 1
frame_start_index = 0
frame_count = 1

[sprites.item_heart.animations.empty]
row = 2
frame_start_index = 0
frame_count = 1

# UI

[sprites.ui_healthbar]
sprite_sheet_file_name = "ui/healthbar.png"
image_width = 256
image_height = 99

[sprites.ui_healthbar.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1


[sprites.main_menu_backdrop]
sprite_sheet_file_name = "ui/title.png"
image_width = 480
image_height = 270

[sprites.main_menu_backdrop.animations.idle]
row = 0
frame_start_index = 0
frame_count = 1



















# Scenery

# UI

[sprites.house_1]
sprite_sheet_file_name = "sprites/scenery/house_1.png"
image_width = 128
image_height = 128

[sprites.house_1.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.house_1.animations.glowing]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.lamp_post]
sprite_sheet_file_name = "sprites/scenery/lamp_post.png"
image_width = 24
image_height = 48

[sprites.lamp_post.animations.idle]
row = 0
frame_start_index = 0
frame_count = 3

[sprites.lamp_post.animations.swinging]
row = 1
frame_start_index = 0
frame_count = 4
