[sprites.terminal]
sprite_sheet_file_name = "sprites/terminal.png"
image_width = 32
image_height = 32
[sprites.terminal.animations.idle]
row = 0
frame_start_index = 0
frame_count = 4




[sprites.player_attack]
sprite_sheet_file_name = "sprites/attack.png"
image_width = 64
image_height = 64

[sprites.player_attack.animations.down]
row = 0
frame_start_index = 0
frame_count = 5

[sprites.player_attack.animations.horizontal]
row = 1
frame_start_index = 0
frame_count = 5






[sprites.chest_simple]
sprite_sheet_file_name = "sprites/chest_simple.png"
image_width = 16
image_height = 16

[sprites.chest_simple.animations.locked]
row = 0
frame_start_index = 0
frame_count = 1

[sprites.chest_simple.animations.opening]
row = 1
frame_start_index = 0
frame_count = 6

[sprites.chest_simple.animations.open]
row = 1
frame_start_index = 5
frame_count = 1




# Enemies

[sprites.what_sprite]
sprite_sheet_file_name = "sprites/enemies/the_what.png"
image_width = 32
image_height = 32

[sprites.what_sprite.animations.run]
row = 0
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.idle]
row = 1
frame_start_index = 0
frame_count = 4

[sprites.what_sprite.animations.death]
row = 2
frame_start_index = 0
frame_count = 5

[sprites.what_sprite.animations.dead]
row = 2
frame_start_index = 4
frame_count = 1